language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install coveralls
  - pip install coverage
  - pip install pylint==1.9.3
script:
  - pylint cheat
  - python -m unittest discover
  - coverage run -m unittest discover
  - coverage report -m
after_success:
    coveralls
