language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install coveralls
  - pip install coverage
  - pip install pylint==2.3.1
script:
  - pylint cheat
  - python -m unittest discover
  - coverage run -m unittest discover
  - coverage report -m
after_success:
    coveralls
